import type { Metadata } from "next";
import "../../assets/styles/globals.css";
import { NavbarAdmin } from "@/shared/components/navbar-admin";
import { MenuList } from "@/shared/components/navbar-admin/menu-list";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Providers>
        <div className="flex flex-col xs:flex-row w-full h-screen">
          <NavbarAdmin className="block xs:hidden" />
          <aside className="border-r-2 border-zinc-300 w-[200px] hidden xs:block">
            <div className="p-4">
              <span className="text-primary-600 font-bold">Jabes</span>
            </div>
            <div className="mt-4 border-t-2 border-zinc-300 p-4">
              <MenuList />
            </div>
          </aside>
          <section className="w-ful xs:w-[calc(100%-200px)] h-full p-4">
            {children}
          </section>
        </div>
      </Providers>
    </>
  );
}
